### ISSUE TITLE
Re export netlink-* dependencies

### ISSUE THREAD

**Issue by jeanhdex** [rust-netlink/rtnetlink#28]
Sometimes, one may need to import netlink-X dependencies for matching purposes. Here is an example:

```rust
let mac = link
        .nlas
        .iter()
        .find_map(|i| match i {
            netlink_packet_route::rtnl::link::nlas::Nla::Address(a) => Some(a),
            _ => None,
        });
```

In this example, including the `netlink_packet_route` crate with the `version = "*"` option may confuse cargo. Cargo will use the latest version (in our example `0.16`) even if the `rtnetlink` crate is still using a previous version (`0.15` in our example).

A workaround for this problem would be to re-export all netlink crate in rtnetlink, so one will only have to include one dependency (rtnetlink) without caring about broken dependencies.

Let me know if that's a good idea or if there are other solutions and I'll be very happy to create a new pull request for this problem!

**Comment by cathay4t** [comment]
Rexport `netlink-packet-route` in `rtnetlink` means every time `netlink-packet-route` has semver bump, `rtnetlink` need to.

In general, I agree this is improving the user experience.

Can we do this after we reach 1.0 API stable?

**Comment by cathay4t** [comment]
I noticed, if rtnetlink does not bump semver when netlink-packet-route, we will get compile failure complaining about two version of crate been used.

Let's expose it as `route`, please proceed to create a PR. Thank you!

**Comment by cathay4t** [comment]
@little-dude What do you think on reexporting rust-netlink crates used by rtnetlink?

In usage, I noticed it is a pain to include 3+ crate dependency into `Cargo.toml` in order to use it. So I would vote yes.

**Comment by little-dude** [comment]
I'd also vote yes to that :+1:
