### ISSUE TITLE
API to add vrf links is missing

### ISSUE THREAD

**Issue by timoschwarzer** [rust-netlink/rtnetlink#40]
The library is missing an API to add a link with `InfoKind::Vrf`. It would be great if that could be added to `LinkAddRequest`, or even make all the request functions `name()`, `link_info()`, `append_nla()`, `up()` etc) public.

**Comment by cathay4t** [comment]
The `LinkAddRequest::message_mut()` could be used as temporary workaround. But yes, that feature should be served.

I don't have time for this, seeing help.

**Comment by daniel-noland** [comment]
Thanks for marking this as a good first issue, this helped me get started on this code base.

I think I did it correctly in #59.  Let me know if you want any changes.
